config/routes.rb
Rails.application.routes.draw do
   root to: "public#homepage"

   # pages
  get '/help', to: 'public#help'
  get '/about', to: 'public#about'
  get '/contact', to: 'public#contact'

  # sessions
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # users
   resources :users
   resources :posts do
  resources :comments
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/jobs/application_job.rb
class ApplicationJob < ActiveJob::Base
  # Automatically retry jobs that encountered a deadlock
  # retry_on ActiveRecord::Deadlocked

  # Most jobs are safe to ignore if the underlying records are no longer available
  # discard_on ActiveJob::DeserializationError
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :upload_photo
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

    before_save { self.email = email.downcase }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :username, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }

                      has_many :posts,dependent: :destroy


  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comments = @post.comments.create(params[:comments].permit(:name, :body))
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    post = current_user.posts.create(post_params)
     if post.save
      redirect_to user_path(current_user)
     else
       redirect_to user_path(current_user)
     end
   end

def edit
 @post = Post.find(params[:id])
end

def update
 @post = Post.find(params[:id])
 @post.update(post_params)
 if @post.save
  redirect_to user_path(current_user)
 else
   redirect_to user_path(current_user)
 end
end

def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to user_path(current_user)
end



   private
     def post_params
       params.require(:post).permit(:caption, :upload_photo)

     end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def homepage
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  user = User.find_by(email: params[:session][:email])
  if user && user.authenticate(params[:session][:password])
    log_in user
    redirect_to user_path(user)
  else
    flash.now[:danger] = 'Invalid email/password combination'
    render 'new'
  end
end

    def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
     @user = User.new
   end

   def create
     @user = User.create(user_params)
     if @user.save
        redirect_to user_path(@user), notice: 'You have successfully signed up.'
     else
       render 'new'
     end
   end

  def edit
  end

   def show
     @user = User.find(params[:id])
   end

   private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    end
  end

  #Logs out the given user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/comment/comments.html.erb
<%= comments.name %>
<%= comments.body %>
<%= time_ago_in_words(comments.created_at) %>

app/views/comments/comments.html.erb
<%= comments.name %>
<%= comments.body %>
<%= time_ago_in_words(comments.created_at) %>

app/views/comments/form.html.erb
<%= form_for{[@post.@post.comments.build]} do |f| %>
<p>
  <%= f.<label :body %><br>
  <%= f.text_area :body %>
</p>
<br>
<p>
  <%= f.sumbit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<p>dsfjkndsjkbfdskjfb</p>

app/views/posts/edit.html.erb
<h1> Edit your posts, <%= @post.user.username %></h1>

<%= form_for @post do |f| %>
<%= f.file_field :upload_photo %>
<%= f.text_field :caption, placeholder:'Caption' %>
<%= f.submit 'Post' %>
<% end %>

app/views/posts/show.html.erb
<h1> <%= @post.comments.count %> Comments </h1>
<%= render @post.comments %>
 <h2> Add a comments: </h2>
 <%= render 'comments/form' %>

app/views/shared/_header.html.erb
<% if logged_in? %>
   <%= link_to "Home", root_path %>
   <%= link_to "Profile", user_path(current_user) %>
   <%= link_to "Log out", logout_path, method: :delete %>
<% else
   <%= link_to "Log in", login_path %>
 <% end %>

app/views/users/new.html.erb
<h1>This is sign up</h1>

<%= form_for User.new do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.username %></h1>
<%= link_to "Log out", logout_path, method: :delete %>



<h7> Feed </h7>
<%= form_for current_user.posts.new do |f| %>
     <%= f.file_field :upload_photo %>
     <%= f.text_field :caption, placeholder: 'Description' %>
     <%= f.submit 'Upload' %>
<% end %>

 <% @user.posts.all.each do |post| %>
     <%= image_tag post.upload_photo, style: "width: 200px; display: block;" %>
     <%= post.caption %>
     <%=link_to 'edit', edit_post_path(post) %>
     <%=link_to 'delete', post_path(post), method: :delete %>
 <% end %>